# Generated by Django 3.2.4 on 2022-04-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0002_unread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unread',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
